image: alpine
stages:
  - compile
  - test
  - package
  - delpoy

compile:
  stage: compile
  script: 
  - echo "------------------CreateFile Started------------------"
  - ls -la
  - echo "Build by Gitlab" >> index.html
  - cat index.html
  - echo "--------------------File Finished---------------------"

test:
  stage: test
  script:
  - echo "-------------------Test Started-----------------------"
  - result=$(grep "Hello" index.html | wc -l)
  - echo $result
  - if [ "$result" = "1" ]
  - then
  - echo "Test Passed"
  - else
  - echo "Test Failed"
  - exit 1
  - fi
  - echo "--------------------Test Finished---------------------"

package:
  stage: package
  script: cat index.html | gzip > package.gz
  artifacts:
    paths:
    - package.gz

delpoy:
  stage: delpoy
  before_script: 
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$admin_key_stockholm" >> ~/.ssh/ssh_key
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 600 ~/.ssh/ssh_key
  - ls -la
  script:
  - scp -i ~/.ssh/ssh_key package.gz ec2-user@13.48.123.71:/var/www/html/
  - ssh -T ec2-user@13.48.123.71 -i ~/.ssh/ssh_key "gunzip -c package.gz > index.html && sudo service httpd restart"
